fieldLayouts:
  c71ae864-2972-4f18-a9e5-6839f1ee8626:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1036cda0-74b6-4e7f-8db8-ccd3b5a423ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5edf3f64-12fc-4fd8-aa67-1f3ea36616e8 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be557e4e-5d7f-4851-80dd-175e46cdb78f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f94ca16-453f-4ff9-84b4-1154a8a813d2 # Event Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9b75cfe-9c83-40ed-af10-befb8c4d2e57
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fdbff045-cab1-42dc-ae29-9dbba859c671
        userCondition: null
fs: events
handle: events
name: Events
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
