fieldLayouts:
  9715c5cb-f656-4f16-a01d-9d1fdf83c660:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 108f86f4-4153-4610-b87a-6a7024a2a49b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e96f6721-be18-4ff8-8aab-4121f8e8a14a # Instagram Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f07892c0-8f00-4fa7-ac47-ca1eacdac49d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e015fc6d-4621-42ae-9fc7-aeb4bb2ab82d # Discord Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bdf9150-e265-481b-a767-97761e9bd8bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17225af9-d8fa-496e-84de-b0932e0cb269 # LinkedIn
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59545fd3-d9d6-4a2e-ae83-7c42ca403d63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60328176-6db4-4d10-b844-6100d1446ee8 # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ac206fb-0c43-469c-9172-2dcc72c8dd38
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59ab9f93-38c7-48b1-8d65-d403357be975
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
section: c3e93172-32cc-4582-897b-4fec759ed794 # Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
