fieldLayouts:
  44f90d48-56a2-4ceb-96ec-797309b68bf7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: 'Homepage title'
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8a6c9e5d-8194-4b24-b012-c8e6ed2f482a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4501e90a-915d-4cd9-8d90-831f7592197a # Subtext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26971a82-1fd5-4df1-8b7a-fb6e642f2f3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53e8b5f5-cedf-4544-b9ca-38f645b7dd6c # Survey URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 543aea02-bef6-47a6-bd59-e4f09df8c029
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3bd1a57d-9346-4983-b119-ca59d3f56c67
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: d57181d9-bf62-4cd2-8922-f3f3ae7ee70f # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
