fieldLayouts:
  1ff14365-9b0a-435e-ba89-9841cda37dd0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9435edd5-4138-4abe-9578-2671eb830121
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5edf3f64-12fc-4fd8-aa67-1f3ea36616e8 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 951e546a-331e-4325-ada4-8369fe437553
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f008490-425e-4b37-9531-2fb47fc3d24b
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 765c4e88-d809-4d54-80cc-57e653985857 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
