fieldLayouts:
  2c9a2811-cf73-4007-87f5-14ba9b7a4c68:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ff727586-804e-4e6b-aff0-f1c9f2e6249a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5edf3f64-12fc-4fd8-aa67-1f3ea36616e8 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2227a2b7-3ec2-4f4c-afb6-df3886131e26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7f94ca16-453f-4ff9-84b4-1154a8a813d2 # Event Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24e7ad3f-edf0-438f-8b11-1f673e690c6f
            userCondition: null
            warning: null
            width: 100
        name: Events
        uid: 90b19f72-19b9-4c5c-8cd8-efb89c33dbf8
        userCondition: null
handle: events
hasTitleField: true
name: Events
section: 71b7a124-0908-470a-90c9-ddb43c64eabd # Events
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
