columnSuffix: cotpoqwd
contentColumnType: datetime
fieldGroup: 087e0c6f-1168-48dd-b338-2bc4bdf4e93d # Events
handle: date
instructions: null
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
