columnSuffix: qdskawly
contentColumnType: time
fieldGroup: 087e0c6f-1168-48dd-b338-2bc4bdf4e93d # Events
handle: endTime
instructions: null
name: 'End Time'
searchable: false
settings:
  max: '21:00'
  min: '06:00'
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
