fieldLayouts:
  519fcb17-49ba-430b-b2b3-77274b228dc5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 706317e0-9093-472f-adf0-201ebb71a8c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99091ca9-f4f5-4bfa-83af-b7c0c09fe0f8
        userCondition: null
fs: favicon
handle: favicon
name: Favicon
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
