defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  025f765b-22cc-4651-a46e-0da4cba5388d: # ubcaccs.ca
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: contact-page
type: single
