dateModified: 1714508411
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
        - 'field:7f94ca16-453f-4ff9-84b4-1154a8a813d2' # Event Image
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:71b7a124-0908-470a-90c9-ddb43c64eabd' # Events
      type: native
email:
  fromEmail: ubcaccs@gmail.com
  fromName: ubcaccs.ca
  transportType: craft\mail\transportadapters\Sendmail
fs:
  events:
    hasUrls: true
    name: Events
    settings:
      path: '@webroot/images/uploads/events'
    type: craft\fs\Local
    url: '@web/images/uploads/events'
meta:
  __names__:
    5e93ae0f-d6a1-4d7f-88d7-37a8f2c68196: ubcaccs.ca # ubcaccs.ca
    5edf3f64-12fc-4fd8-aa67-1f3ea36616e8: Description # Description
    06c4324d-71fe-476a-9b1f-3e6feaecf1ac: 'Public Schema' # Public Schema
    7f94ca16-453f-4ff9-84b4-1154a8a813d2: 'Event Image' # Event Image
    025f765b-22cc-4651-a46e-0da4cba5388d: ubcaccs.ca # ubcaccs.ca
    59ef1311-cc39-4344-a00d-5fa511f77a36: '350x350 Event' # 350x350 Event
    71b7a124-0908-470a-90c9-ddb43c64eabd: Events # Events
    087e0c6f-1168-48dd-b338-2bc4bdf4e93d: Events # Events
    765c4e88-d809-4d54-80cc-57e653985857: About # About
    b9e65696-21d4-4990-a67a-05cd8555b297: Events # Events
    cc729cab-7cdb-489c-ab4f-7a0b60e804e3: About # About
    d759efbd-e6b8-46d7-b600-312486821a48: Common # Common
    db94afb7-2344-4381-a3df-07d2072312a7: Events # Events
system:
  edition: solo
  live: true
  name: ubcaccs.ca
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
