defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  025f765b-22cc-4651-a46e-0da4cba5388d: # ubcaccs.ca
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
